# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-29 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('surname', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
