# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20180509_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='app_images'),
        ),
    ]
